#!/bin/sh
## Set the name of the job in the queuing system
#PBS -N HW4_husun

#PBS -A stats_flux
#PBS -l qos=flux
#PBS -q flux

#PBS -l nodes=4:ppn=4
#PBS -l walltime=01:00:00

#PBS -o /home/husun/STATS506/HW4/problem2b
#PBS -V

#PBS -m abe


#PBS -M husun@umich.edu

#PBS -l pmem=4Gb

#PBS -j oe

#PBS -V

##code to be run
R CMD BATCH --vanilla /home/husun/STATS506/HW4/problem2b/ps4_q2b.R /home/husun/STATS506/HW4/problem2b/ps4_q2b.Rout
